# Build stage
FROM maven:3.6.0-jdk-11-slim AS build
COPY javulna/src /home/app/src
COPY javulna/pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package

# Package stage
FROM openjdk:11-jre-slim
COPY --from=build /home/app/target/javulna-1.0-SNAPSHOT.jar /usr/local/lib/javulna.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/local/lib/javulna.jar"]
